version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: "@open-wa/wa-automate"
    versions:
    - 3.10.10
    - 3.10.11
    - 3.10.13
    - 3.10.14
    - 3.10.15
    - 3.10.4
    - 3.10.5
    - 3.10.8
    - 3.11.1
    - 3.11.4
    - 3.6.1
    - 3.6.13
    - 3.6.5
    - 3.7.0
    - 3.9.1
    - 3.9.13
    - 3.9.14
    - 3.9.15
    - 3.9.16
    - 3.9.2
    - 3.9.5
    - 3.9.6
  - dependency-name: "@tensorflow/tfjs-node"
    versions:
    - 3.2.0
    - 3.3.0
    - 3.4.0
  - dependency-name: yt-search
    versions:
    - 2.7.4
    - 2.7.5
    - 2.7.6
  - dependency-name: tiktok-scraper
    versions:
    - 1.4.15
    - 1.4.16
    - 1.4.17
    - 1.4.18
    - 1.4.19
    - 1.4.20
  - dependency-name: html-entities
    versions:
    - 2.1.1
  - dependency-name: mathjs
    versions:
    - 9.3.0
  - dependency-name: tape
    versions:
    - 5.2.1
    - 5.2.2
  - dependency-name: canvacord
    versions:
    - 5.1.0
  - dependency-name: got
    versions:
    - 11.8.2
  - dependency-name: puppeteer
    versions:
    - 6.0.0
    - 7.0.0
    - 7.0.4
    - 8.0.0
  - dependency-name: google-it
    versions:
    - 1.6.2
